CHARGEMENT DES DOSSIERS CSV

Utilisation de pandas

In [64]:
import pandas as pd
df = pd.read_csv("immo.csv")
df.head()

,id,prix,superficie_m2,nb_chambres,nb_etages,localisation,acces_route,eau_electricite,type_connexion,parking,type_sol,etat_maison,annee_construction
0,107.0,129.0,70.0,1.0,2.0,periurbain,0,non,fibre,1,ciment,neuf,1992.0
1,5484.0,210.0,69.0,5.0,2.0,urbain,Yes,non,starlink,1,brut,bon,2003.0
2,6998.0,397.0,223.0,2.0,2.0,urbain,1,0,aucune,oui,carrelage,bon,1998.0
3,3984.0,221.0,185.0,1.0,NaN,urbain,non,No,starlink,non,ciment,a_renover,2015.0
4,3111.0,80.0,NaN,2.0,1.0,periurbain,oui,oui,fibre,non,brut,a_renover,2007.0

COMPTER LIGNES

In [65]:
len(df)

10000

VERIFICATION DES VALEURS MANQUANTES

In [66]:
df.isnull().sum()

id                    508
prix                  504
superficie_m2         493
nb_chambres           493
nb_etages             512
localisation          504
acces_route           505
eau_electricite       491
type_connexion        508
parking               512
type_sol              498
etat_maison           514
annee_construction    501
dtype: int64

 VERIFIACATION DES DOUBLONS

In [67]:
df.duplicated(subset=['id']).sum()

np.int64(1286)

AFFICHER

In [68]:
df[df.duplicated(subset=['id'], keep=False)]

,id,prix,superficie_m2,nb_chambres,nb_etages,localisation,acces_route,eau_electricite,type_connexion,parking,type_sol,etat_maison,annee_construction
6,3013.0,273.0,222.0,5.0,1.0,rural,0,oui,starlink,No,carrelage,neuf,1997.0
19,5226.0,220.0,171.0,2.0,2.0,NaN,No,NaN,aucune,non,carrelage,a_renover,2015.0
20,3088.0,314.0,243.0,3.0,2.0,urbain,NaN,No,starlink,non,ciment,a_renover,2014.0
21,NaN,404.0,156.0,1.0,NaN,urbain,oui,Yes,aucune,oui,ciment,neuf,2012.0
25,381.0,97.0,81.0,1.0,NaN,periurbain,0,No,aucune,non,brut,bon,2016.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9980,9099.0,130.0,54.0,5.0,1.0,urbain,0,Yes,starlink,No,NaN,a_renover,NaN
9984,3778.0,112.0,117.0,3.0,1.0,periurbain,1,non,aucune,Yes,carrelage,a_renover,NaN
9993,950.0,338.0,239.0,5.0,NaN,NaN,Yes,0,aucune,No,carrelage,a_renover,2008.0
9996,419.0,313.0,183.0,1.0,1.0,urbain,No,Yes,fibre,Yes,carrelage,bon,1990.0
9999,NaN,86.0,55.0,5.0,2.0,periurbain,Yes,0,fibre,No,ciment,a_renover,2017.0

NETTOYAGE

1 : Suppression des valeurs manquantes

2 : Suppression des doublons

In [69]:
df = df.dropna()

In [70]:
df = df.drop_duplicates()

DEUXIEME VERIFICATION MANQUANTES ET DOUBLONS

In [71]:
df.isnull().sum()

id                    0
prix                  0
superficie_m2         0
nb_chambres           0
nb_etages             0
localisation          0
acces_route           0
eau_electricite       0
type_connexion        0
parking               0
type_sol              0
etat_maison           0
annee_construction    0
dtype: int64

In [72]:
df.duplicated(subset=['id']).sum()

np.int64(0)

AFFICHAGE DES TOUS LES COLLONNES UTILISEES

In [73]:

print(df.columns)

Index(['id', 'prix', 'superficie_m2', 'nb_chambres', 'nb_etages',
       'localisation', 'acces_route', 'eau_electricite', 'type_connexion',
       'parking', 'type_sol', 'etat_maison', 'annee_construction'],
      dtype='object')

In [74]:
print(list(df.columns))

['id', 'prix', 'superficie_m2', 'nb_chambres', 'nb_etages', 'localisation', 'acces_route', 'eau_electricite', 'type_connexion', 'parking', 'type_sol', 'etat_maison', 'annee_construction']

In [75]:
for col in df.columns:
    print(col)

id
prix
superficie_m2
nb_chambres
nb_etages
localisation
acces_route
eau_electricite
type_connexion
parking
type_sol
etat_maison
annee_construction

ETAPE 4 : INFORMATIONS DE TYPES DES COLONNES

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4745 entries, 0 to 9998
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  4745 non-null   float64
 1   prix                4745 non-null   float64
 2   superficie_m2       4745 non-null   float64
 3   nb_chambres         4745 non-null   float64
 4   nb_etages           4745 non-null   float64
 5   localisation        4745 non-null   object
 6   acces_route         4745 non-null   object
 7   eau_electricite     4745 non-null   object
 8   type_connexion      4745 non-null   object
 9   parking             4745 non-null   object
 10  type_sol            4745 non-null   object
 11  etat_maison         4745 non-null   object
 12  annee_construction  4745 non-null   float64
dtypes: float64(6), object(7)
memory usage: 519.0+ KB

ETAPE 5 : INSPECTION DES TYPES OBJETS

In [77]:
obj_cols = df.select_dtypes(include='object')

print(obj_cols.columns)

Index(['localisation', 'acces_route', 'eau_electricite', 'type_connexion',
       'parking', 'type_sol', 'etat_maison'],
      dtype='object')

In [78]:
for col in obj_cols.columns:
    print(f"Colonne: {col}")
    print(df[col].unique())

Colonne: localisation
['periurbain' 'urbain' 'rural']
Colonne: acces_route
['0' 'Yes' '1' 'non' 'No' 'oui']
Colonne: eau_electricite
['non' '0' 'oui' '1' 'No' 'Yes']
Colonne: type_connexion
['fibre' 'starlink' 'aucune']
Colonne: parking
['1' 'oui' 'Yes' 'No' '0' 'non']
Colonne: type_sol
['ciment' 'brut' 'carrelage']
Colonne: etat_maison
['neuf' 'bon' 'a_renover']

In [79]:
for col in obj_cols.columns:
    print(f"{col} → {df[col].nunique()} valeurs uniques")

localisation → 3 valeurs uniques
acces_route → 6 valeurs uniques
eau_electricite → 6 valeurs uniques
type_connexion → 3 valeurs uniques
parking → 6 valeurs uniques
type_sol → 3 valeurs uniques
etat_maison → 3 valeurs uniques

NETTOYAGE PAR TYPE

UNIFORMISATION

In [80]:
df['acces_route'] = df['acces_route'].str.strip().str.lower()

In [81]:
df['eau_electricite'] = df['eau_electricite'].str.strip().str.lower()

In [82]:
df['parking'] = df['parking'].str.strip().str.lower()

In [83]:
df['type_sol'] = df['type_sol'].str.strip().str.lower()

In [84]:
df['etat_maison'] = df['etat_maison'].str.strip().str.lower()

In [85]:
df['type_connexion'] = df['type_connexion'].str.strip().str.lower()

In [86]:
df['localisation'] = df['localisation'].str.strip().str.lower()

TYPE OBJETS

CREATION MAPPING

In [87]:
mapping = {
    '0': False,
    'no': False,
    'non': False,
    '1': True,
    'yes': True,
    'oui': True
}

ACCES ROUTE

APPLICATION DE LA TRANSFORMATION

In [88]:
df['acces_route'] = df['acces_route'].map(mapping)

DEUXIEME VERIFICATIONS

In [89]:
for col in obj_cols.columns:
    print(f"Colonne: {col}")
    print(df[col].unique())

Colonne: localisation
['periurbain' 'urbain' 'rural']
Colonne: acces_route
[False  True]
Colonne: eau_electricite
['non' '0' 'oui' '1' 'no' 'yes']
Colonne: type_connexion
['fibre' 'starlink' 'aucune']
Colonne: parking
['1' 'oui' 'yes' 'no' '0' 'non']
Colonne: type_sol
['ciment' 'brut' 'carrelage']
Colonne: etat_maison
['neuf' 'bon' 'a_renover']

In [90]:
print(df['acces_route'].unique())
print(df['acces_route'].dtype)

[False  True]
bool

EAU ET ELECTRICITE

In [91]:
df['eau_electricite'] = df['eau_electricite'].map(mapping)

In [92]:
for col in obj_cols.columns:
    print(f"Colonne: {col}")
    print(df[col].unique())

Colonne: localisation
['periurbain' 'urbain' 'rural']
Colonne: acces_route
[False  True]
Colonne: eau_electricite
[False  True]
Colonne: type_connexion
['fibre' 'starlink' 'aucune']
Colonne: parking
['1' 'oui' 'yes' 'no' '0' 'non']
Colonne: type_sol
['ciment' 'brut' 'carrelage']
Colonne: etat_maison
['neuf' 'bon' 'a_renover']

PARKING

In [93]:
df['parking'] = df['parking'].map(mapping)

In [94]:
for col in obj_cols.columns:
    print(f"Colonne: {col}")
    print(df[col].unique())

Colonne: localisation
['periurbain' 'urbain' 'rural']
Colonne: acces_route
[False  True]
Colonne: eau_electricite
[False  True]
Colonne: type_connexion
['fibre' 'starlink' 'aucune']
Colonne: parking
[ True False]
Colonne: type_sol
['ciment' 'brut' 'carrelage']
Colonne: etat_maison
['neuf' 'bon' 'a_renover']

VERIFICATION DES VALEURS

VALEURS NEGATIVES

In [95]:
cols = ['prix', 'superficie_m2', 'nb_chambres', 'nb_etages']

for col in cols:
    print(col, (df[col] < 0).sum())

prix 0
superficie_m2 0
nb_chambres 0
nb_etages 0

VOIR DES LIGNES CHOISI

PREMIER LIGNE

In [96]:
df.head(30)

,id,prix,superficie_m2,nb_chambres,nb_etages,localisation,acces_route,eau_electricite,type_connexion,parking,type_sol,etat_maison,annee_construction
0,107.0,129.0,70.0,1.0,2.0,periurbain,False,False,fibre,True,ciment,neuf,1992.0
1,5484.0,210.0,69.0,5.0,2.0,urbain,True,False,starlink,True,brut,bon,2003.0
2,6998.0,397.0,223.0,2.0,2.0,urbain,True,False,aucune,True,carrelage,bon,1998.0
5,4040.0,135.0,67.0,5.0,1.0,periurbain,False,False,fibre,True,carrelage,bon,2013.0
6,3013.0,273.0,222.0,5.0,1.0,rural,False,True,starlink,False,carrelage,neuf,1997.0
7,6607.0,194.0,71.0,4.0,2.0,urbain,False,True,starlink,False,ciment,bon,2022.0
8,4219.0,91.0,105.0,3.0,2.0,rural,False,False,starlink,False,brut,bon,2002.0
10,5665.0,114.0,106.0,1.0,2.0,rural,False,False,starlink,False,ciment,neuf,2004.0
11,9225.0,47.0,61.0,1.0,1.0,rural,False,True,starlink,True,brut,bon,2008.0
12,8030.0,277.0,229.0,3.0,1.0,periurbain,False,False,aucune,False,ciment,bon,2000.0
14,1851.0,362.0,207.0,2.0,1.0,periurbain,False,False,aucune,True,brut,neuf,1995.0
16,3043.0,185.0,53.0,5.0,2.0,urbain,True,False,aucune,True,ciment,bon,2023.0
17,3369.0,147.0,116.0,2.0,2.0,periurbain,False,True,aucune,True,carrelage,bon,1993.0
18,6829.0,383.0,202.0,3.0,2.0,urbain,True,True,aucune,False,brut,bon,1994.0
23,4993.0,545.0,202.0,2.0,1.0,urbain,True,False,fibre,False,brut,neuf,2022.0
24,4209.0,189.0,157.0,2.0,1.0,periurbain,True,True,aucune,True,ciment,bon,1998.0
30,8412.0,370.0,175.0,5.0,2.0,periurbain,True,True,starlink,False,ciment,neuf,1995.0
36,5938.0,101.0,72.0,2.0,1.0,periurbain,True,True,fibre,False,ciment,bon,2009.0
40,4786.0,439.0,244.0,3.0,1.0,periurbain,True,False,aucune,True,ciment,neuf,2005.0
41,2602.0,301.0,227.0,5.0,2.0,periurbain,True,True,fibre,True,brut,bon,2006.0
42,7779.0,90.0,128.0,1.0,1.0,rural,False,False,aucune,False,ciment,bon,1991.0
43,2826.0,143.0,172.0,2.0,2.0,periurbain,False,False,fibre,False,brut,a_renover,1990.0
44,1118.0,392.0,220.0,2.0,2.0,urbain,False,True,fibre,False,ciment,bon,2020.0
47,8654.0,307.0,103.0,2.0,2.0,urbain,True,True,aucune,True,carrelage,neuf,2006.0
48,7719.0,212.0,141.0,5.0,1.0,periurbain,False,False,fibre,True,ciment,bon,1992.0
49,6575.0,273.0,181.0,5.0,2.0,urbain,False,False,fibre,False,brut,a_renover,1991.0
51,7234.0,424.0,114.0,5.0,2.0,urbain,False,True,starlink,True,brut,neuf,2018.0
52,8366.0,207.0,70.0,5.0,1.0,periurbain,False,False,fibre,False,carrelage,neuf,1995.0
53,3948.0,110.0,93.0,1.0,2.0,periurbain,True,False,fibre,False,carrelage,bon,2013.0
57,2820.0,115.0,86.0,2.0,1.0,periurbain,False,False,aucune,False,brut,bon,1990.0

DERNIER LIGNE

In [97]:
df.tail(20)

,id,prix,superficie_m2,nb_chambres,nb_etages,localisation,acces_route,eau_electricite,type_connexion,parking,type_sol,etat_maison,annee_construction
9961,9831.0,96.0,201.0,1.0,1.0,rural,False,False,starlink,True,carrelage,a_renover,2004.0
9962,7790.0,149.0,108.0,2.0,2.0,urbain,True,True,aucune,True,ciment,a_renover,1999.0
9964,7783.0,89.0,174.0,2.0,2.0,rural,True,False,fibre,False,carrelage,a_renover,1990.0
9965,2443.0,179.0,110.0,5.0,1.0,periurbain,False,False,fibre,True,carrelage,bon,2005.0
9968,814.0,128.0,163.0,3.0,1.0,rural,False,True,aucune,False,brut,bon,2018.0
9969,6166.0,97.0,101.0,4.0,2.0,rural,False,True,fibre,False,ciment,bon,2019.0
9970,5779.0,278.0,211.0,3.0,2.0,urbain,True,False,aucune,False,ciment,a_renover,1992.0
9972,793.0,190.0,235.0,5.0,2.0,rural,False,True,fibre,True,carrelage,bon,2004.0
9973,6898.0,82.0,159.0,2.0,2.0,rural,True,False,fibre,True,carrelage,a_renover,2003.0
9978,2891.0,297.0,240.0,2.0,1.0,urbain,True,True,starlink,False,brut,a_renover,1994.0
9979,2371.0,232.0,195.0,1.0,1.0,urbain,True,False,fibre,False,ciment,a_renover,2012.0
9983,6359.0,410.0,200.0,5.0,2.0,periurbain,True,True,aucune,True,brut,neuf,2018.0
9987,1865.0,144.0,67.0,2.0,1.0,periurbain,False,True,aucune,True,brut,neuf,1992.0
9988,4612.0,125.0,55.0,2.0,1.0,periurbain,True,False,aucune,True,carrelage,neuf,2010.0
9990,2243.0,99.0,196.0,2.0,2.0,rural,False,False,starlink,False,carrelage,a_renover,1990.0
9991,5373.0,209.0,149.0,3.0,2.0,urbain,False,True,starlink,False,carrelage,a_renover,2005.0
9992,2336.0,80.0,129.0,4.0,1.0,rural,False,True,fibre,False,brut,a_renover,1998.0
9995,2204.0,222.0,163.0,4.0,2.0,periurbain,False,True,aucune,False,brut,bon,2008.0
9997,922.0,356.0,210.0,1.0,2.0,urbain,False,False,fibre,False,brut,bon,2008.0
9998,9446.0,75.0,104.0,5.0,2.0,rural,True,False,aucune,True,carrelage,a_renover,2021.0

ALEATOIRES

In [98]:
df.sample(10)

,id,prix,superficie_m2,nb_chambres,nb_etages,localisation,acces_route,eau_electricite,type_connexion,parking,type_sol,etat_maison,annee_construction
1280,465.0,93.0,115.0,1.0,1.0,periurbain,False,True,starlink,False,brut,a_renover,1991.0
5497,1876.0,312.0,150.0,4.0,2.0,periurbain,False,True,starlink,True,brut,neuf,1992.0
118,2492.0,113.0,80.0,3.0,2.0,rural,False,True,fibre,True,brut,neuf,2018.0
1108,2357.0,105.0,97.0,1.0,1.0,rural,True,True,aucune,True,ciment,neuf,2016.0
398,9679.0,90.0,175.0,2.0,1.0,rural,False,False,aucune,True,ciment,a_renover,2002.0
9546,2396.0,105.0,51.0,4.0,2.0,periurbain,True,False,aucune,True,carrelage,bon,1998.0
8646,8964.0,342.0,157.0,5.0,1.0,periurbain,True,True,fibre,True,carrelage,neuf,1999.0
1356,92.0,112.0,142.0,1.0,1.0,periurbain,True,False,fibre,True,ciment,a_renover,2017.0
9647,9323.0,637.0,203.0,5.0,1.0,urbain,False,False,fibre,False,ciment,neuf,2011.0
4370,1480.0,82.0,132.0,4.0,1.0,rural,True,False,starlink,True,ciment,a_renover,1995.0

COMPTER LIGNES

EVALUATION

In [99]:
len(df)

4745

In [100]:
df.describe()

,id,prix,superficie_m2,nb_chambres,nb_etages,annee_construction
count,4745.000000,4745.000000,4745.000000,4745.000000,4745.000000,4745.000000
mean,5007.845522,218.264489,148.984615,2.967756,1.490832,2006.581665
std,2880.406750,133.690155,58.288891,1.425945,0.499969,9.896605
min,0.000000,31.000000,50.000000,1.000000,1.000000,1990.000000
25%,2515.000000,118.000000,98.000000,2.000000,1.000000,1998.000000
50%,5006.000000,186.000000,149.000000,3.000000,1.000000,2007.000000
75%,7520.000000,283.000000,200.000000,4.000000,2.000000,2015.000000
max,9995.000000,748.000000,249.000000,5.000000,2.000000,2023.000000

AFFICHAGE MIN ET MAX

In [101]:
df.agg(['min', 'max'])

,id,prix,superficie_m2,nb_chambres,nb_etages,localisation,acces_route,eau_electricite,type_connexion,parking,type_sol,etat_maison,annee_construction
min,0.0,31.0,50.0,1.0,1.0,periurbain,False,False,aucune,False,brut,a_renover,1990.0
max,9995.0,748.0,249.0,5.0,2.0,urbain,True,True,starlink,True,ciment,neuf,2023.0

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4745 entries, 0 to 9998
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  4745 non-null   float64
 1   prix                4745 non-null   float64
 2   superficie_m2       4745 non-null   float64
 3   nb_chambres         4745 non-null   float64
 4   nb_etages           4745 non-null   float64
 5   localisation        4745 non-null   object
 6   acces_route         4745 non-null   bool
 7   eau_electricite     4745 non-null   bool
 8   type_connexion      4745 non-null   object
 9   parking             4745 non-null   bool
 10  type_sol            4745 non-null   object
 11  etat_maison         4745 non-null   object
 12  annee_construction  4745 non-null   float64
dtypes: bool(3), float64(6), object(4)
memory usage: 421.7+ KB

MODIFICATIONS DE TYPES

On change les types des colonnes pour avoir des normes et logiques des données

In [103]:
df['localisation'] = df['localisation'].astype('category')

In [104]:
df['type_connexion'] = df['type_connexion'].astype('category')

In [105]:
df['type_sol'] = df['type_sol'].astype('category')

In [106]:
df['etat_maison'] = df['etat_maison'].astype('category')

In [107]:
df['prix'] = df['prix'].astype('int')

In [108]:
df['nb_chambres'] = df['nb_chambres'].astype('int')

In [109]:
df['nb_etages'] = df['nb_etages'].astype('int')

In [110]:
df['id'] = df['id'].astype('int')

In [111]:
df['id'] = df['id'].astype('int')

In [112]:
df['annee_construction'] = df['annee_construction'].astype('int')

In [113]:
print(df['id'].dtype)

int64

CHANGEMENT DES NOMS D'UN COLONNES

On change le prix  en million d'ariary

In [114]:
df.rename(columns={'prix': 'prix_million_ariary'}, inplace=True)

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4745 entries, 0 to 9998
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   4745 non-null   int64
 1   prix_million_ariary  4745 non-null   int64
 2   superficie_m2        4745 non-null   float64
 3   nb_chambres          4745 non-null   int64
 4   nb_etages            4745 non-null   int64
 5   localisation         4745 non-null   category
 6   acces_route          4745 non-null   bool
 7   eau_electricite      4745 non-null   bool
 8   type_connexion       4745 non-null   category
 9   parking              4745 non-null   bool
 10  type_sol             4745 non-null   category
 11  etat_maison          4745 non-null   category
 12  annee_construction   4745 non-null   int64
dtypes: bool(3), category(4), float64(1), int64(5)
memory usage: 292.4 KB

SAUVEGARDE FICHIER NETTOYEE

In [116]:

df.to_csv('immobilier_nettoye.csv', index=False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')